/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Ventanas;

import java.awt.event.ItemEvent;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import java.util.ArrayList;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author USUARIO
 */
public class Nota_Rendimiento extends javax.swing.JFrame {
    Connection base;
    Principal padre;
    int ultima_nota;
    int posicion_cosecha;
    int posicion_orden_trilla;
    int posicion_café;
    int tabla_trilla;
    int tabla_cafe;
    
    //ArrayList donde llevo un control sobre la informacion que contienen los JcomoboBox
    ArrayList<String> Id_cosecha;
    ArrayList<String> Id_cafe;
    ArrayList<String> Id_orden_trilla;
    
    //ArrayList donde tengo el id de las ordenes de trilla que van a pertenecer a la nota de rendimiento a crear 
    ArrayList<String> Ordenes_agregadas;
    
    //ArrayList donde tengo el id de las ordenes de trilla que van a pertenecer a la nota de rendimiento a crear 
    ArrayList<String> id_cafe_obtenido;
    
    /**
     * Creates new form Nota_Rendimiento
     */
    public Nota_Rendimiento() {
        initComponents();
    }
    
    public Nota_Rendimiento(Connection base, Principal padre) throws SQLException {
        initComponents();
        this.base = base;
        this.padre = padre;
        tabla_trilla = -1;
        posicion_cosecha =-1;
        tabla_cafe = -1;
        posicion_orden_trilla =-1;
        posicion_café = -1;
        Id_cosecha = new ArrayList<>();
        Id_cafe = new ArrayList<>();
        Id_orden_trilla = new ArrayList<>();
        Ordenes_agregadas = new ArrayList<>();
        id_cafe_obtenido = new ArrayList<>();
        Statement b = base.createStatement();
        ResultSet consultab = b.executeQuery("Select cosecha.Id,cosecha.Nombre FROM cosecha ORDER BY cosecha.Id DESC;");
        while(consultab.next()){
            String Id = consultab.getString(1);
            String nombre = consultab.getString(2);
            Id_cosecha.add(Id);
            tx_cosecha.addItem(nombre);
        }
        b = base.createStatement();
        consultab = b.executeQuery("SELECT MAX(notarendimiento.Codigo) FROM notarendimiento;");
        if(consultab.next()) ultima_nota = consultab.getInt(1);
        b= base.createStatement();
        consultab = b.executeQuery("Select cafe.Id,cafe.Nombre FROM cafe WHERE cafe.Oro = 1;");
        while(consultab.next()){
            String id = consultab.getString(1);
            String nombre = consultab.getString(2);
            Id_cafe.add(id);
            res_tipo.addItem(nombre);
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        tx_cosecha = new javax.swing.JComboBox<>();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        da_numero = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        da_Marcas = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        da_fecha = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        da_num_embarque = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        da_puerto = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        da_exportar = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        da_sacos = new javax.swing.JTextField();
        jLabel10 = new javax.swing.JLabel();
        da_imperfecciones = new javax.swing.JTextField();
        jPanel2 = new javax.swing.JPanel();
        jLabel11 = new javax.swing.JLabel();
        ot_codigo = new javax.swing.JComboBox<>();
        jLabel12 = new javax.swing.JLabel();
        ot_fecha = new javax.swing.JTextField();
        jLabel13 = new javax.swing.JLabel();
        ot_preparacion = new javax.swing.JTextField();
        jLabel14 = new javax.swing.JLabel();
        ot_marcas = new javax.swing.JTextField();
        jLabel15 = new javax.swing.JLabel();
        ot_cliente = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        Ordenes_Trilla = new javax.swing.JTable();
        jLabel16 = new javax.swing.JLabel();
        ot_cafe_utilizado = new javax.swing.JTextField();
        jButton5 = new javax.swing.JButton();
        jLabel24 = new javax.swing.JLabel();
        jLabel25 = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        jLabel18 = new javax.swing.JLabel();
        res_tipo = new javax.swing.JComboBox<>();
        jLabel19 = new javax.swing.JLabel();
        res_cantidad = new javax.swing.JTextField();
        jLabel20 = new javax.swing.JLabel();
        res_sacos = new javax.swing.JTextField();
        jScrollPane2 = new javax.swing.JScrollPane();
        Resultados = new javax.swing.JTable();
        jButton4 = new javax.swing.JButton();
        jButton6 = new javax.swing.JButton();
        jLabel26 = new javax.swing.JLabel();
        jLabel27 = new javax.swing.JLabel();
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jLabel21 = new javax.swing.JLabel();
        jLabel22 = new javax.swing.JLabel();
        jLabel17 = new javax.swing.JLabel();
        jLabel23 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        tx_cosecha.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                tx_cosechaItemStateChanged(evt);
            }
        });

        jLabel1.setText("Cosecha");

        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder(new javax.swing.border.MatteBorder(null), "Datos"));

        jLabel3.setText("No.");

        da_numero.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                da_numeroKeyPressed(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                da_numeroKeyTyped(evt);
            }
        });

        jLabel4.setText("Marcas:");

        jLabel5.setText("Fecha de Embarque:");

        jLabel6.setText("No. de Embarque:");

        jLabel7.setText("Puerto de Embarque:");

        jLabel8.setText("Café a Exportar:");

        jLabel9.setText("No. Sacos:");

        jLabel10.setText("Imperfecciones:");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel1Layout.createSequentialGroup()
                                .addComponent(jLabel5)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(da_fecha))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addContainerGap()
                                .addComponent(jLabel3)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(da_numero, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(49, 49, 49)
                                .addComponent(jLabel4)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(da_Marcas)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jLabel6)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(da_num_embarque))))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel7)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(da_puerto))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel8)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(da_exportar, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(48, 48, 48)
                        .addComponent(jLabel9)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(da_sacos, javax.swing.GroupLayout.PREFERRED_SIZE, 77, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(55, 55, 55)
                        .addComponent(jLabel10)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(da_imperfecciones, javax.swing.GroupLayout.PREFERRED_SIZE, 83, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(da_numero, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel4)
                    .addComponent(da_Marcas, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(da_fecha, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel6)
                    .addComponent(da_num_embarque, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel7)
                    .addComponent(da_puerto, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel8)
                    .addComponent(da_exportar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel9)
                    .addComponent(da_sacos, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel10)
                    .addComponent(da_imperfecciones, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(0, 11, Short.MAX_VALUE))
        );

        jPanel2.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)), "Ordenes de Trilla"));

        jLabel11.setText("No.");

        ot_codigo.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                ot_codigoItemStateChanged(evt);
            }
        });

        jLabel12.setText("Fecha:");

        ot_fecha.setEditable(false);

        jLabel13.setText("Preparación:");

        ot_preparacion.setEditable(false);

        jLabel14.setText("Marcas:");

        ot_marcas.setEditable(false);

        jLabel15.setText("Cliente:");

        ot_cliente.setEditable(false);

        jButton1.setText("Agregar");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        Ordenes_Trilla.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "No. de Orden", "Preparación", "Marcas", "Quintales"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        Ordenes_Trilla.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                Ordenes_TrillaMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(Ordenes_Trilla);
        if (Ordenes_Trilla.getColumnModel().getColumnCount() > 0) {
            Ordenes_Trilla.getColumnModel().getColumn(0).setResizable(false);
            Ordenes_Trilla.getColumnModel().getColumn(0).setPreferredWidth(30);
            Ordenes_Trilla.getColumnModel().getColumn(1).setResizable(false);
            Ordenes_Trilla.getColumnModel().getColumn(1).setPreferredWidth(50);
            Ordenes_Trilla.getColumnModel().getColumn(2).setResizable(false);
            Ordenes_Trilla.getColumnModel().getColumn(2).setPreferredWidth(200);
            Ordenes_Trilla.getColumnModel().getColumn(3).setResizable(false);
            Ordenes_Trilla.getColumnModel().getColumn(3).setPreferredWidth(50);
        }

        jLabel16.setText("qq Utilizados:");

        ot_cafe_utilizado.setEditable(false);

        jButton5.setText("Borrar");
        jButton5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton5ActionPerformed(evt);
            }
        });

        jLabel24.setText("Total Café Utilizado: ");

        jLabel25.setText("jLabel25");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addGroup(jPanel2Layout.createSequentialGroup()
                                    .addComponent(jLabel11)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addComponent(ot_codigo, javax.swing.GroupLayout.PREFERRED_SIZE, 95, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGap(33, 33, 33)
                                    .addComponent(jLabel12)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addComponent(ot_fecha, javax.swing.GroupLayout.PREFERRED_SIZE, 101, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGroup(jPanel2Layout.createSequentialGroup()
                                    .addComponent(jLabel14)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addComponent(ot_marcas)))
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addGap(114, 114, 114)
                                .addComponent(jLabel16)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(ot_cafe_utilizado, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jLabel13)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(ot_preparacion))
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addGap(95, 95, 95)
                                .addComponent(jButton1)
                                .addGap(0, 135, Short.MAX_VALUE))
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addGap(9, 9, 9)
                                .addComponent(jLabel15)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(ot_cliente))))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                        .addComponent(jLabel24)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel25, javax.swing.GroupLayout.PREFERRED_SIZE, 137, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jButton5)
                        .addGap(124, 124, 124))))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel11)
                    .addComponent(ot_codigo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel12)
                    .addComponent(ot_fecha, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel13)
                    .addComponent(ot_preparacion, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel14)
                    .addComponent(ot_marcas, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel15)
                    .addComponent(ot_cliente, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton1)
                    .addComponent(ot_cafe_utilizado, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel16))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 146, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton5)
                    .addComponent(jLabel24)
                    .addComponent(jLabel25))
                .addContainerGap())
        );

        jPanel3.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)), "Resultados"));

        jLabel18.setText("Tipo de Café: ");

        res_tipo.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                res_tipoItemStateChanged(evt);
            }
        });
        res_tipo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                res_tipoActionPerformed(evt);
            }
        });

        jLabel19.setText("Cantidad: ");

        res_cantidad.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                res_cantidadActionPerformed(evt);
            }
        });
        res_cantidad.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                res_cantidadKeyTyped(evt);
            }
        });

        jLabel20.setText("No. Sacos");

        Resultados.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Tipo de Café", "Quintales", "No. de Sacos"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class, java.lang.Object.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        Resultados.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                ResultadosMouseClicked(evt);
            }
        });
        jScrollPane2.setViewportView(Resultados);
        if (Resultados.getColumnModel().getColumnCount() > 0) {
            Resultados.getColumnModel().getColumn(0).setResizable(false);
            Resultados.getColumnModel().getColumn(0).setPreferredWidth(300);
            Resultados.getColumnModel().getColumn(1).setResizable(false);
            Resultados.getColumnModel().getColumn(1).setPreferredWidth(50);
            Resultados.getColumnModel().getColumn(2).setResizable(false);
            Resultados.getColumnModel().getColumn(2).setPreferredWidth(50);
        }

        jButton4.setText("Agregar");
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });

        jButton6.setText("Borrar");
        jButton6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton6ActionPerformed(evt);
            }
        });

        jLabel26.setText("Total Café Obtendio: ");

        jLabel27.setText("jLabel27");

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jScrollPane2)
                            .addGroup(jPanel3Layout.createSequentialGroup()
                                .addComponent(jLabel18)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(res_tipo, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jLabel19)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(res_cantidad, javax.swing.GroupLayout.PREFERRED_SIZE, 117, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jLabel20)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(res_sacos, javax.swing.GroupLayout.PREFERRED_SIZE, 59, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addContainerGap())
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(jButton4)
                        .addGap(26, 26, 26))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                        .addComponent(jLabel26)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel27, javax.swing.GroupLayout.PREFERRED_SIZE, 172, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 35, Short.MAX_VALUE)
                        .addComponent(jButton6)
                        .addGap(225, 225, 225))))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel18)
                    .addComponent(res_tipo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel19)
                    .addComponent(res_cantidad, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel20)
                    .addComponent(res_sacos, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jButton4)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 180, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton6)
                    .addComponent(jLabel26)
                    .addComponent(jLabel27))
                .addContainerGap(14, Short.MAX_VALUE))
        );

        jButton2.setText("Crear");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        jButton3.setText("Regresar");

        jLabel21.setText("Rendimiento Bruto:");

        jLabel22.setText("Renidimiento Neto:");

        jLabel17.setText("jLabel17");

        jLabel23.setText("jLabel23");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(4, 4, 4)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(jLabel2))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 10, Short.MAX_VALUE)))
                .addContainerGap())
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel1)
                .addGap(18, 18, 18)
                .addComponent(tx_cosecha, javax.swing.GroupLayout.PREFERRED_SIZE, 158, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(518, 518, 518))
            .addGroup(layout.createSequentialGroup()
                .addGap(152, 152, 152)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jButton2)
                        .addGap(18, 18, 18)
                        .addComponent(jButton3)
                        .addGap(70, 70, 70))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(99, 99, 99)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel22)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jLabel23))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel21)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jLabel17)))
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(17, 17, 17)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(tx_cosecha, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel1))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(68, 68, 68)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jLabel21)
                                    .addComponent(jLabel17))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jLabel22)
                                    .addComponent(jLabel23)))
                            .addGroup(layout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(11, 11, 11)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(229, 229, 229)
                                .addComponent(jLabel2)
                                .addGap(0, 0, Short.MAX_VALUE))
                            .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(30, 30, 30)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jButton2)
                            .addComponent(jButton3))))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void res_cantidadActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_res_cantidadActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_res_cantidadActionPerformed

    private void da_numeroKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_da_numeroKeyPressed
        
    }//GEN-LAST:event_da_numeroKeyPressed

    private void da_numeroKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_da_numeroKeyTyped
        char code = evt.getKeyChar();
        if(code == '|'){
            evt.consume();
           da_numero.setText(Integer.toString(ultima_nota+1));
           
        } 
    }//GEN-LAST:event_da_numeroKeyTyped

    private void tx_cosechaItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_tx_cosechaItemStateChanged
        if(evt.getStateChange() == ItemEvent.SELECTED){
            Actualizar();
            
        }
    }//GEN-LAST:event_tx_cosechaItemStateChanged

    private void ot_codigoItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_ot_codigoItemStateChanged
        if(evt.getStateChange() == ItemEvent.SELECTED){
            Statement b;
            posicion_orden_trilla = ot_codigo.getSelectedIndex();
            try {
                b = base.createStatement();
                ResultSet consultab = b.executeQuery("SELECT ordentrilla.Fecha,ordentrilla.Cliente,ordentrilla.Preparacion,ordentrilla.Marca,ordentrilla.CafeUsado FROM ordentrilla WHERE ordentrilla.Codigo = "+Id_orden_trilla.get(posicion_orden_trilla)+";");
                if(consultab.next()){
                    ot_fecha.setText(consultab.getString(1));
                    ot_cliente.setText(consultab.getString(2));
                    ot_preparacion.setText(consultab.getString(3));
                    ot_marcas.setText(consultab.getString(4));
                    ot_cafe_utilizado.setText(consultab.getString(5));
                }
            } catch (SQLException ex) {
                Logger.getLogger(Nota_Rendimiento.class.getName()).log(Level.SEVERE, null, ex);
            }
            
        }
    }//GEN-LAST:event_ot_codigoItemStateChanged

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        if(posicion_orden_trilla!= -1){
            String codigo = (String)ot_codigo.getSelectedItem();
            if(!Ordenes_agregadas.contains(codigo)){
                DefaultTableModel tabla = (DefaultTableModel)Ordenes_Trilla.getModel();
                String[] agregar = new String[4];
                agregar[0] = codigo;
                agregar[1] = ot_preparacion.getText();
                agregar[2] = ot_marcas.getText();
                agregar[3] = ot_cafe_utilizado.getText();
                tabla.addRow(agregar);
                Ordenes_agregadas.add(codigo);
            }else{
                JOptionPane.showMessageDialog(this, "La orden ya ha sido agregada", "ERROR", JOptionPane.ERROR_MESSAGE, null);
            }
            
        }
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton5ActionPerformed
        if(tabla_trilla != -1){
            DefaultTableModel tabla = (DefaultTableModel)Ordenes_Trilla.getModel();
            String Id = (String)tabla.getValueAt(tabla_trilla, 0);
            tabla.removeRow(tabla_trilla);
            Ordenes_agregadas.remove(Id);
            tabla_trilla = -1;
        }else{
            JOptionPane.showMessageDialog(this, "Debe seleccionar una fila", "ERROR", JOptionPane.ERROR_MESSAGE, null);
        }
    }//GEN-LAST:event_jButton5ActionPerformed

    private void res_tipoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_res_tipoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_res_tipoActionPerformed

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
        if(posicion_café!= -1){
            String Id = Id_cafe.get(posicion_café);
            if(!id_cafe_obtenido.contains(Id)){
            String tipo = (String)res_tipo.getSelectedItem();
            String cantidad = res_cantidad.getText().trim();
            String sacos = res_sacos.getText().trim();
            if(cantidad.length() > 0 && sacos.length() >0){
                String[] agregar = new String[3];
                agregar[0] = tipo;
                agregar[1] = cantidad;
                agregar[2] = sacos;
                id_cafe_obtenido.add(Id_cafe.get(posicion_café));
                DefaultTableModel tabla = (DefaultTableModel) Resultados.getModel();
                tabla.addRow(agregar);
            }else{
                JOptionPane.showMessageDialog(this, "Debe llenar todos los campos", "ERROR", JOptionPane.ERROR_MESSAGE, null);
            }
            }else{
                JOptionPane.showMessageDialog(this, "Este tipo ya ha sido agregado", "ERROR", JOptionPane.ERROR_MESSAGE, null);
            }
        }
    }//GEN-LAST:event_jButton4ActionPerformed

    private void res_tipoItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_res_tipoItemStateChanged
        if(evt.getStateChange() == ItemEvent.SELECTED){
            posicion_café = res_tipo.getSelectedIndex();
        }
    }//GEN-LAST:event_res_tipoItemStateChanged

    private void res_cantidadKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_res_cantidadKeyTyped
        // TODO add your handling code here:
    }//GEN-LAST:event_res_cantidadKeyTyped

    private void jButton6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton6ActionPerformed
        if(tabla_cafe != -1){
            DefaultTableModel tabla = (DefaultTableModel)Resultados.getModel();
            tabla.removeRow(tabla_cafe);
            id_cafe_obtenido.remove(tabla_cafe);
            tabla_cafe = -1;
        }else{
            JOptionPane.showMessageDialog(this, "Debe seleccionar una fila", "ERROR", JOptionPane.ERROR_MESSAGE, null);
        }
        
    }//GEN-LAST:event_jButton6ActionPerformed

    private void ResultadosMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_ResultadosMouseClicked
        tabla_cafe = Resultados.getSelectedRow();
    }//GEN-LAST:event_ResultadosMouseClicked

    private void Ordenes_TrillaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Ordenes_TrillaMouseClicked
        tabla_trilla = Ordenes_Trilla.getSelectedRow();
    }//GEN-LAST:event_Ordenes_TrillaMouseClicked

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        String Numero = da_numero.getText().trim();
        if(Numero.length()>0){
            String Marca = da_Marcas.getText().trim();
            String Exportar = da_exportar.getText().trim();
            String Sacos = da_sacos.getText().trim();
            String imperfecciones = da_imperfecciones.getText().trim();
            if(Marca.length()>0 && Exportar.length() > 0 && Sacos.length()>0 && imperfecciones.length()>0){
                if(Ordenes_agregadas.size()>0 && id_cafe_obtenido.size()>0){
                    if(id_cafe_obtenido.contains("1")){
                        Statement b;
                        try {
                            b = base.createStatement();
                            ResultSet consultab = b.executeQuery("SELECT notarendimiento.Codigo FROM notarendimiento WHERE notarendimiento.Codigo = "+Numero+";");
                            if(!consultab.next()){
                                //Obtengo el resto de información que ingresa el usuario
                                String Fecha_embarque = ""+ da_fecha.getText().trim();
                                String Numero_embarque = ""+da_num_embarque.getText().trim();
                                String Puerto_embarque = ""+da_puerto.getText().trim();
                                int posicion_exportación = id_cafe_obtenido.indexOf("1");
                                // calculo el saldo de cafe
                                float vendido = Float.parseFloat(Exportar);
                                float Exportación = Float.parseFloat((String)Resultados.getValueAt(posicion_exportación, 1));
                                String saldo = String.format("%.2f", Exportación-vendido);
                                
                                //Crear la nueva nota de rendimiento
                                String instruccion = "INSERT INTO notarendimiento(codigo,cosecha_id,fechanota,marca,fechaembarque,numembarque,numsacos,pesoaexportar,imperfecciones,puertoembarque,saldo) VALUES("+Numero+","+Id_cosecha.get(posicion_cosecha)+",NOW(),'"+Marca+"','"+Fecha_embarque+"','"+Numero_embarque+"',"+Sacos+","+Exportar+","+imperfecciones+",'"+Puerto_embarque+"',"+saldo+");";
                                PreparedStatement pst = base.prepareStatement(instruccion);
                                pst.executeUpdate();
                                
                                //Realizo la relacion de las ordenes de trilla con las notas de rendimiento
                                int Numero_Ordenes = Ordenes_Trilla.getRowCount();
                                for (int i = 0; i < Numero_Ordenes; i++) {
                                    String ordentrilla =(String) Ordenes_Trilla.getValueAt(i, 0);
                                    instruccion = "UPDATE  ordentrilla SET ordentrilla.NotaRendimiento_Codigo = "+Numero+",ordentrilla.Disponible = 0 WHERE ordentrilla.Codigo = "+ordentrilla+";";
                                    PreparedStatement actualización = base.prepareStatement(instruccion);
                                    actualización.executeUpdate();
                                }
                                
                                // Creo los nuevos ingresos de café oro 
                                int Numero_resultados = Resultados.getRowCount();
                                for (int i = 0; i < Numero_resultados; i++) {
                                    String Id_cafe = id_cafe_obtenido.get(i);
                                    String peso_final = (String) Resultados.getValueAt(i, 1);
                                    String cant_sacos = (String) Resultados.getValueAt(i, 2);
                                    instruccion = "INSERT INTO producto(producto.NotaRendimiento_Codigo,producto.Cafe_Id,producto.PesoFinal,producto.CantidadSacos) VALUES("+Numero+","+Id_cafe+","+peso_final+","+cant_sacos+");";
                                    PreparedStatement agregar = base.prepareStatement(instruccion);
                                    agregar.executeUpdate();      
                                }
                                
                                consultab = b.executeQuery("SELECT MAX(notarendimiento.Codigo) FROM notarendimiento;");
                                if(consultab.next()) ultima_nota = consultab.getInt(1);
                                Actualizar();
                                //Dejar limpio los campos de ingreso de datos y reiniciar el proceso
                                da_Marcas.setText("");
                                da_exportar.setText("");
                                da_fecha.setText("");
                                da_imperfecciones.setText("");
                                da_num_embarque.setText("");
                                da_numero.setText("");
                                da_puerto.setText("");
                                da_sacos.setText("");
                                id_cafe_obtenido = new ArrayList<>();
                                Ordenes_agregadas = new ArrayList<>();
                                DefaultTableModel a = (DefaultTableModel)Ordenes_Trilla.getModel();
                                a.setRowCount(0);
                                DefaultTableModel bs = (DefaultTableModel)Resultados.getModel();
                                bs.setRowCount(0);
                                
                            }
                        else{
                            JOptionPane.showMessageDialog(this, "Ya existe una nota de Rendimiento con este numero", "ERROR", JOptionPane.ERROR_MESSAGE, null);
                        }
                        } catch (SQLException ex) {
                            Logger.getLogger(Nota_Rendimiento.class.getName()).log(Level.SEVERE, null, ex);
                        }
                        
                    }else{
                        JOptionPane.showMessageDialog(this, "El Café Exportacion es necesario", "ERROR", JOptionPane.ERROR_MESSAGE, null);
        
                    }
                }else{
                    JOptionPane.showMessageDialog(this, "Es necesario almenos una orden de trilla y un tipo de cafe", "ERROR", JOptionPane.ERROR_MESSAGE, null);
        
                }
            }else{
                JOptionPane.showMessageDialog(this, "La marca, café a exportar, No.Sacos e imperfecciones son necesarios", "ERROR", JOptionPane.ERROR_MESSAGE, null);
            }
            
        }
        else{
            JOptionPane.showMessageDialog(this, "El numero de nota de Rendimiento es necesario", "ERROR", JOptionPane.ERROR_MESSAGE, null);
        }
    }//GEN-LAST:event_jButton2ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Nota_Rendimiento.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Nota_Rendimiento.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Nota_Rendimiento.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Nota_Rendimiento.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Nota_Rendimiento().setVisible(true);
            }
        });
    }
    
    public void Actualizar(){
       
        Statement b;
            posicion_cosecha = tx_cosecha.getSelectedIndex();
            Id_orden_trilla = new ArrayList<>();
            ot_codigo.removeAllItems();
            ot_cafe_utilizado.setText("");
            ot_cliente.setText("");
            ot_fecha.setText("");
            ot_marcas.setText("");
            ot_preparacion.setText("");
            
            try {
                b = base.createStatement();
                ResultSet consultab = b.executeQuery("SELECT ordentrilla.Codigo FROM ordentrilla WHERE ordentrilla.Disponible = 1 && ordentrilla.Cosecha_Id = "+Id_cosecha.get(posicion_cosecha)+";");
                while(consultab.next()){
                    String Id = consultab.getString(1);
                    Id_orden_trilla.add(Id);
                    ot_codigo.addItem(Id);
                }
            } catch (SQLException ex) {
                Logger.getLogger(Nota_Rendimiento.class.getName()).log(Level.SEVERE, null, ex);
            }
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTable Ordenes_Trilla;
    private javax.swing.JTable Resultados;
    private javax.swing.JTextField da_Marcas;
    private javax.swing.JTextField da_exportar;
    private javax.swing.JTextField da_fecha;
    private javax.swing.JTextField da_imperfecciones;
    private javax.swing.JTextField da_num_embarque;
    private javax.swing.JTextField da_numero;
    private javax.swing.JTextField da_puerto;
    private javax.swing.JTextField da_sacos;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JButton jButton5;
    private javax.swing.JButton jButton6;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel23;
    private javax.swing.JLabel jLabel24;
    private javax.swing.JLabel jLabel25;
    private javax.swing.JLabel jLabel26;
    private javax.swing.JLabel jLabel27;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTextField ot_cafe_utilizado;
    private javax.swing.JTextField ot_cliente;
    private javax.swing.JComboBox<String> ot_codigo;
    private javax.swing.JTextField ot_fecha;
    private javax.swing.JTextField ot_marcas;
    private javax.swing.JTextField ot_preparacion;
    private javax.swing.JTextField res_cantidad;
    private javax.swing.JTextField res_sacos;
    private javax.swing.JComboBox<String> res_tipo;
    private javax.swing.JComboBox<String> tx_cosecha;
    // End of variables declaration//GEN-END:variables
}
