/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Ventanas;

import Conexion.ConectarConBD;
import java.sql.Connection;

/**
 *
 * @author USUARIO
 */
public class Principal extends javax.swing.JFrame {
    private final Connection conexion;
    /**
     * Creates new form Principal
     */
    public Principal() {
        initComponents();
        ConectarConBD obtenerConexion = new ConectarConBD();
        conexion = obtenerConexion.getConexion();
        if (conexion == null)
            System.exit(0);
        this.setLocationRelativeTo(null);   // Para centrar esta ventana sobre la pantalla.
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        menu = new javax.swing.JMenuBar();
        menu_crear = new javax.swing.JMenu();
        item_crear_cosecha = new javax.swing.JMenuItem();
        jMenuItem2 = new javax.swing.JMenuItem();
        jMenuItem5 = new javax.swing.JMenuItem();
        item_crear_tipo_cafe = new javax.swing.JMenuItem();
        jMenu2 = new javax.swing.JMenu();
        jMenuItem8 = new javax.swing.JMenuItem();
        jMenuItem9 = new javax.swing.JMenuItem();
        jMenuItem10 = new javax.swing.JMenuItem();
        jMenu3 = new javax.swing.JMenu();
        jMenuItem3 = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        menu_crear.setText("Crear");

        item_crear_cosecha.setText("Cosecha");
        item_crear_cosecha.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                item_crear_cosechaActionPerformed(evt);
            }
        });
        menu_crear.add(item_crear_cosecha);

        jMenuItem2.setText("Organización");
        menu_crear.add(jMenuItem2);

        jMenuItem5.setText("Productor");
        menu_crear.add(jMenuItem5);

        item_crear_tipo_cafe.setText("Tipo de Cafe");
        item_crear_tipo_cafe.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                item_crear_tipo_cafeActionPerformed(evt);
            }
        });
        menu_crear.add(item_crear_tipo_cafe);

        menu.add(menu_crear);

        jMenu2.setText("Producción");

        jMenuItem8.setText("Recibo");
        jMenuItem8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem8ActionPerformed(evt);
            }
        });
        jMenu2.add(jMenuItem8);

        jMenuItem9.setText("Orden de Trilla");
        jMenuItem9.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem9ActionPerformed(evt);
            }
        });
        jMenu2.add(jMenuItem9);

        jMenuItem10.setText("Nota de Rendimiento");
        jMenu2.add(jMenuItem10);

        menu.add(jMenu2);

        jMenu3.setText("Inventario");

        jMenuItem3.setText("Ver Recibos");
        jMenuItem3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem3ActionPerformed(evt);
            }
        });
        jMenu3.add(jMenuItem3);

        menu.add(jMenu3);

        setJMenuBar(menu);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 648, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 434, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void item_crear_cosechaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_item_crear_cosechaActionPerformed
        CrearCosecha nuevaCosecha = new CrearCosecha(this, true, conexion);
        nuevaCosecha.setVisible(nuevaCosecha.getHacerVisible());
    }//GEN-LAST:event_item_crear_cosechaActionPerformed

    private void item_crear_tipo_cafeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_item_crear_tipo_cafeActionPerformed
        CrearTipoCafe nuevoCafe = new CrearTipoCafe(this, true, conexion);
        nuevoCafe.setVisible(nuevoCafe.getHacerVisible());
    }//GEN-LAST:event_item_crear_tipo_cafeActionPerformed

    private void jMenuItem8ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem8ActionPerformed
        Recibo nuevoRecibo = new Recibo(this, true, conexion);
        nuevoRecibo.setVisible(nuevoRecibo.getHacerVisible());
    }//GEN-LAST:event_jMenuItem8ActionPerformed

    private void jMenuItem9ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem9ActionPerformed
        OrdenTrilla nuevaOrden = new OrdenTrilla(this, true, conexion);
        nuevaOrden.setVisible(nuevaOrden.getHacerVisible());
    }//GEN-LAST:event_jMenuItem9ActionPerformed

    private void jMenuItem3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem3ActionPerformed
        InventarioRecibos nuevoInventarioRecibos = new InventarioRecibos(conexion);
        nuevoInventarioRecibos.setVisible(nuevoInventarioRecibos.getHacerVisible());
    }//GEN-LAST:event_jMenuItem3ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Principal().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenuItem item_crear_cosecha;
    private javax.swing.JMenuItem item_crear_tipo_cafe;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenu jMenu3;
    private javax.swing.JMenuItem jMenuItem10;
    private javax.swing.JMenuItem jMenuItem2;
    private javax.swing.JMenuItem jMenuItem3;
    private javax.swing.JMenuItem jMenuItem5;
    private javax.swing.JMenuItem jMenuItem8;
    private javax.swing.JMenuItem jMenuItem9;
    private javax.swing.JMenuBar menu;
    private javax.swing.JMenu menu_crear;
    // End of variables declaration//GEN-END:variables
}
